# Generated by Django 6.0 on 2025-12-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wifi_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='sem-email@example.com', max_length=100, unique=True),
        ),
    ]
