# Generated by Django 6.0 on 2025-12-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wifi_scanner', '0002_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('redes', models.JSONField(default=list)),
                ('total_networks', models.IntegerField(default=0)),
                ('avg_signal', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_scans', to='app_wifi_scanner.usuario')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
